openapi: 3.0.3
info:
  title: API Library
  version: 1.0.0
  description: API REST para gestionar una biblioteca

servers:
  - url: http://localhost:8082

paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuario creado

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un usuario por ID
      responses:
        '200':
          description: Usuario encontrado
        '404':
          description: Usuario no encontrado
    put:
      summary: Actualizar un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuario actualizado
    patch:
      summary: Actualizar parcialmente un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Usuario actualizado parcialmente
    delete:
      summary: Eliminar un usuario
      responses:
        '204':
          description: Usuario eliminado

  /books:
    get:
      summary: Obtener todos los libros
      responses:
        '200':
          description: Lista de libros
    post:
      summary: Crear un nuevo libro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Libro creado

  /books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un libro por ID
      responses:
        '200':
          description: Libro encontrado
    put:
      summary: Actualizar un libro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Libro actualizado
    patch:
      summary: Actualizar parcialmente un libro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Libro actualizado parcialmente
    delete:
      summary: Eliminar un libro
      responses:
        '204':
          description: Libro eliminado

  /authors:
    get:
      summary: Obtener todos los autores
      responses:
        '200':
          description: Lista de autores
    post:
      summary: Crear un nuevo autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Autor creado

  /authors/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un autor por ID
      responses:
        '200':
          description: Autor encontrado
    put:
      summary: Actualizar un autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Autor actualizado
    patch:
      summary: Actualizar parcialmente un autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Autor actualizado parcialmente
    delete:
      summary: Eliminar un autor
      responses:
        '204':
          description: Autor eliminado

  /book-categories:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
    post:
      summary: Crear una nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCategory'
      responses:
        '201':
          description: Categoría creada

  /book-categories/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener una categoría por ID
      responses:
        '200':
          description: Categoría encontrada
    put:
      summary: Actualizar una categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCategory'
      responses:
        '200':
          description: Categoría actualizada
    patch:
      summary: Actualizar parcialmente una categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Categoría actualizada parcialmente
    delete:
      summary: Eliminar una categoría
      responses:
        '204':
          description: Categoría eliminada

  /loans:
    get:
      summary: Obtener todos los préstamos
      responses:
        '200':
          description: Lista de préstamos
    post:
      summary: Crear un nuevo préstamo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loan'
      responses:
        '201':
          description: Préstamo creado

  /loans/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Obtener un préstamo por ID
      responses:
        '200':
          description: Préstamo encontrado
    put:
      summary: Actualizar un préstamo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loan'
      responses:
        '200':
          description: Préstamo actualizado
    patch:
      summary: Actualizar parcialmente un préstamo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Préstamo actualizado parcialmente
    delete:
      summary: Eliminar un préstamo
      responses:
        '204':
          description: Préstamo eliminado

components:
  schemas:
    User:
      type: object
      required:
        - name
        - username
        - email
        - password
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        creationDate:
          type: string
          format: date
        active:
          type: boolean
    Book:
      type: object
      required:
        - title
        - pages
      properties:
        id:
          type: integer
        title:
          type: string
        genre:
          type: string
        pages:
          type: integer
        price:
          type: number
        available:
          type: boolean
    Author:
      type: object
      required:
        - name
        - surname
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        birthdate:
          type: string
          format: date
        nationality:
          type: string
        active:
          type: boolean
    BookCategory:
      type: object
      required:
        - name
        - description
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
        createdDate:
          type: string
          format: date
        numberBooks:
          type: integer
    Loan:
      type: object
      required:
        - customerName
        - loanDate
      properties:
        id:
          type: integer
        name:
          type: string
        customerName:
          type: string
        email:
          type: string
        loanDate:
          type: string
          format: date
        quantity:
          type: integer
